Repository Goorm-x-Piggy-Project/server, pull requests merged in 2024-12, with the labels that each got.

#6 [Fix] Config & gateway 빌드 파일 수정
  build.gradle
  config/build.gradle
  config/pom.xml
  gateway/build.gradle
  gateway/pom.xml
  pom.xml
  settings.gradle
Labels: fix

#11 Fix/#8/빌드 툴 마이그레이션
  registry/build.gradle
  registry/pom.xml
  turbine-stream-service/build.gradle
  turbine-stream-service/pom.xml
Labels: fix

#20 [Fix] account service 빌드 자동화 도구 수정
  account-service/build.gradle
  account-service/pom.xml
  account-service/src/main/java/com/piggymetrics/account/AccountApplication.java
  account-service/src/main/resources/application.yml
  build.gradle
  gradlew.bat
Labels: fix, refactor

#26 Fix/#24/turbine stream service 의존성 최신화
  turbine-stream-service/build.gradle
  turbine-stream-service/src/main/java/com/piggymetrics/turbine/TurbineStreamServiceApplication.java
Labels: fix

#29 fix: statistic-service 의존성 최신화
  config/src/main/resources/shared/statistics-service.yml
  statistics-service/build.gradle
  statistics-service/src/main/java/com/piggymetrics/statistics/StatisticsApplication.java
  statistics-service/src/main/java/com/piggymetrics/statistics/client/ExchangeRatesClient.java
  statistics-service/src/main/java/com/piggymetrics/statistics/client/ExchangeRatesClientFallback.java
  statistics-service/src/main/java/com/piggymetrics/statistics/config/ResourceServerConfig.java
  statistics-service/src/main/java/com/piggymetrics/statistics/controller/StatisticsController.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/Account.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/BigDecimalDeserializer.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/Currency.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/ExchangeRatesContainer.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/Item.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/Saving.java
  statistics-service/src/main/java/com/piggymetrics/statistics/repository/DataPointRepository.java
  statistics-service/src/main/java/com/piggymetrics/statistics/repository/converter/DataPointIdReaderConverter.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/ExchangeRatesServiceImpl.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/StatisticsServiceImpl.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/security/CustomUserInfoTokenServices.java
  statistics-service/src/main/resources/bootstrap.yml
  statistics-service/src/test/java/com/piggymetrics/statistics/StatisticsServiceApplicationTests.java
  statistics-service/src/test/java/com/piggymetrics/statistics/client/ExchangeRatesClientTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/client/MongoServerConfig.java
  statistics-service/src/test/java/com/piggymetrics/statistics/controller/StatisticsControllerTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/repository/DataPointRepositoryTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/service/ExchangeRatesServiceImplTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/service/StatisticsServiceImplTest.java
  statistics-service/src/test/resources/application.yml
Labels: fix, refactor

#31 fix: statistic-service 의존성 및 호환성 최신화
  statistics-service/src/main/java/com/piggymetrics/statistics/service/ExchangeRatesService.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/ExchangeRatesServiceImpl.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/StatisticsService.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/StatisticsServiceImpl.java
  statistics-service/src/test/java/com/piggymetrics/statistics/client/ExchangeRatesClientTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/repository/DataPointRepositoryTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/service/ExchangeRatesServiceImplTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/service/StatisticsServiceImplTest.java
  statistics-service/src/test/resources/application-db.yml
Labels: fix

#33 [Fix] account service 호환성 보수 및 코드 수정
  account-service/build.gradle
  account-service/src/main/java/com/piggymetrics/account/AccountApplication.java
  account-service/src/main/java/com/piggymetrics/account/client/AuthServiceClient.java
  account-service/src/main/java/com/piggymetrics/account/client/StatisticsServiceClient.java
  account-service/src/main/java/com/piggymetrics/account/client/StatisticsServiceClientFallback.java
  account-service/src/main/java/com/piggymetrics/account/config/ResourceServerConfig.java
  account-service/src/main/java/com/piggymetrics/account/controller/AccountController.java
  account-service/src/main/java/com/piggymetrics/account/controller/ErrorHandler.java
  account-service/src/main/java/com/piggymetrics/account/domain/Account.java
  account-service/src/main/java/com/piggymetrics/account/domain/Currency.java
  account-service/src/main/java/com/piggymetrics/account/domain/Item.java
  account-service/src/main/java/com/piggymetrics/account/domain/Saving.java
  account-service/src/main/java/com/piggymetrics/account/domain/User.java
  account-service/src/main/java/com/piggymetrics/account/dto/AccountReqDto.java
  account-service/src/main/java/com/piggymetrics/account/dto/AccountResDto.java
  account-service/src/main/java/com/piggymetrics/account/dto/ItemResDto.java
  account-service/src/main/java/com/piggymetrics/account/dto/SavingResDto.java
  account-service/src/main/java/com/piggymetrics/account/dto/UserReqDto.java
  account-service/src/main/java/com/piggymetrics/account/exception/AccountNotFoundException.java
  account-service/src/main/java/com/piggymetrics/account/repository/AccountRepository.java
  account-service/src/main/java/com/piggymetrics/account/service/AccountService.java
  account-service/src/main/java/com/piggymetrics/account/service/AccountServiceImpl.java
  account-service/src/main/java/com/piggymetrics/account/service/security/CustomUserInfoTokenServices.java
  account-service/src/test/java/com/piggymetrics/account/client/StatisticsServiceClientFallbackTest.java
  account-service/src/test/java/com/piggymetrics/account/controller/AccountControllerTest.java
  account-service/src/test/java/com/piggymetrics/account/repository/AccountRepositoryTest.java
  account-service/src/test/java/com/piggymetrics/account/service/AccountServiceTest.java
Labels: fix, feat, refactor

#36 Fix/#35/authservice 리팩토링
  auth-service/build/reports/problems/problems-report.html
  auth-service/src/main/java/com/piggymetrics/auth/controller/UserController.java
  auth-service/src/main/java/com/piggymetrics/auth/domain/User.java
  auth-service/src/main/java/com/piggymetrics/auth/domain/dto/request/UserCreateRequestDto.java
  auth-service/src/main/java/com/piggymetrics/auth/domain/dto/response/UserCreateResponseDto.java
  auth-service/src/main/java/com/piggymetrics/auth/repository/UserRepository.java
  auth-service/src/main/java/com/piggymetrics/auth/service/UserService.java
  auth-service/src/main/java/com/piggymetrics/auth/service/security/MongoUserDetailsService.java
Labels: refactor

#41 [Fix] dockerfile 수정 후 테스트
  .env
  account-service/Dockerfile
  account-service/build.gradle
  account-service/src/main/java/com/piggymetrics/account/config/ResourceServerConfig.java
  account-service/src/main/java/com/piggymetrics/account/controller/AccountController.java
  account-service/src/main/java/com/piggymetrics/account/domain/Item.java
  account-service/src/main/java/com/piggymetrics/account/domain/Saving.java
  account-service/src/main/java/com/piggymetrics/account/domain/User.java
  account-service/src/main/resources/application.yml
  account-service/src/test/java/com/piggymetrics/account/AccountServiceApplicationTests.java
  auth-service/Dockerfile
  config/Dockerfile
  config/src/main/resources/shared/account-service.yml
  config/src/main/resources/shared/application.yml
  config/src/main/resources/shared/gateway.yml
  docker-compose-test.yml
  gateway/Dockerfile
  gateway/src/main/resources/application.yml
  gateway/src/test/java/com/piggymetrics/gateway/GatewayApplicationTests.java
  registry/Dockerfile
  registry/src/main/resources/application.yml
Labels: fix, feat, refactor

#45 Feat#34/모니터링 서비스 구현
  account-service/build.gradle
  account-service/src/main/java/com/piggymetrics/account/client/StatisticsServiceClient.java
  config/src/main/resources/shared/account-service.yml
  config/src/main/resources/shared/application.yml
  config/src/main/resources/shared/gateway.yml
  docker-compose-test.yml
  monitoring/Dockerfile
  monitoring/build.gradle
  monitoring/src/main/java/com/piggymetrics/monitoring/MonitoringApplication.java
  monitoring/src/main/resources/bootstrap.yml
  monitoring/src/test/java/com/piggymetrics/monitoring/MonitoringApplicationTests.java
  monitoring/src/test/resources/bootstrap.yml
  prometheus.yml
  turbine-stream-service/Dockerfile
  turbine-stream-service/build.gradle
  turbine-stream-service/src/main/java/com/piggymetrics/turbine/TurbineStreamServiceApplication.java
  turbine-stream-service/src/main/resources/bootstrap.yml
  turbine-stream-service/src/test/java/com/piggymetrics/turbine/TurbineStreamServiceApplicationTests.java
  turbine-stream-service/src/test/resources/bootstrap.yml
Labels: refactor

#46 Delete .env
  .env
Labels: hot fix

#48 Feat: statistics 프론트 연결 수정
  gateway/src/main/resources/static/js/dashboard.js
  gateway/src/main/resources/static/js/launch.js
  gateway/src/main/resources/static/js/main.js
  statistics-service/src/main/java/com/piggymetrics/statistics/controller/ExchangeRatesController.java
  statistics-service/src/main/java/com/piggymetrics/statistics/controller/StatisticsController.java
  statistics-service/src/main/java/com/piggymetrics/statistics/exception/CustomException.java
  statistics-service/src/main/java/com/piggymetrics/statistics/exception/ErrorResponse.java
  statistics-service/src/main/java/com/piggymetrics/statistics/exception/GlobalExceptionHandler.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/ExchangeRatesService.java
Labels: fix, feat
