Repository Goorm-x-Piggy-Project/server, pull requests merged in 2025-01, with the labels that each got.

#54 refactor: statistics 리팩토링
  statistics-service/build.gradle
  statistics-service/src/main/java/com/piggymetrics/statistics/controller/ExchangeRatesController.java
  statistics-service/src/main/java/com/piggymetrics/statistics/controller/StatisticsController.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/Currency.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/Item.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/Saving.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/timeseries/DataPoint.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/timeseries/DataPointId.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/timeseries/ItemMetric.java
  statistics-service/src/main/java/com/piggymetrics/statistics/exception/ErrorMessages.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/ExchangeRatesService.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/StatisticsService.java
  statistics-service/src/test/java/com/piggymetrics/statistics/client/ExchangeRatesClientTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/client/MongoServerConfig.java
  statistics-service/src/test/java/com/piggymetrics/statistics/controller/StatisticsControllerTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/repository/DataPointRepositoryTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/service/ExchangeRatesServiceImplTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/service/StatisticsServiceImplTest.java
  statistics-service/src/test/resources/application-db.yml
  statistics-service/src/test/resources/application.yml
  statistics-service/src/test/resources/bootstrap.yml
Labels: fix, refactor

#58 [Fix] account service auth service로 올바른 값 전달 및 컨트롤러 반환
  account-service/src/main/java/com/piggymetrics/account/client/StatisticsServiceClient.java
  account-service/src/main/java/com/piggymetrics/account/domain/Account.java
  account-service/src/main/java/com/piggymetrics/account/domain/Currency.java
  account-service/src/main/java/com/piggymetrics/account/dto/AccountReqDto.java
  account-service/src/main/java/com/piggymetrics/account/service/AccountService.java
  docker-compose-test.yml
  gateway/src/main/resources/static/index.html
  gateway/src/main/resources/static/js/main.js
  mongodb/Dockerfile
  statistics-service/build.gradle
  statistics-service/src/main/java/com/piggymetrics/statistics/config/ResourceServerConfig.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/Currency.java
  statistics-service/src/main/java/com/piggymetrics/statistics/dto/AccountReqDto.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/StatisticsService.java
  statistics-service/src/main/resources/application.yml
  statistics-service/src/test/java/com/piggymetrics/statistics/service/ExchangeRatesServiceImplTest.java
Labels: fix, feat, refactor

#60 Fix: 환율 api 검색 날짜 수정
  account-service/src/main/java/com/piggymetrics/account/domain/Currency.java
  statistics-service/src/main/java/com/piggymetrics/statistics/config/ResourceServerConfig.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/Currency.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/ExchangeRatesService.java
Labels: fix

#64 [Fix] 스타일 수정 및 비밀번호 가시성 변경
  account-service/src/main/java/com/piggymetrics/account/service/AccountService.java
  gateway/src/main/resources/static/css/launch.css
  gateway/src/main/resources/static/js/login.js
  statistics-service/src/main/java/com/piggymetrics/statistics/config/ResourceServerConfig.java
Labels: fix, refactor

#66 Fix: 프론트 statistics 화면 연동
  gateway/src/main/resources/static/index.html
  gateway/src/main/resources/static/js/main.js
Labels: fix

#30 [Fix] notification service 의존성 어노테이션 업데이트 및 리팩토링
  config/src/main/resources/shared/gateway.yml
  config/src/main/resources/shared/notification-service.yml
  docker-compose-test.yml
  notification-service/Dockerfile
  notification-service/build.gradle
  notification-service/src/main/java/com/piggymetrics/notification/NotificationServiceApplication.java
  notification-service/src/main/java/com/piggymetrics/notification/client/AccountServiceClient.java
  notification-service/src/main/java/com/piggymetrics/notification/config/MongoConfig.java
  notification-service/src/main/java/com/piggymetrics/notification/config/OAuth2FeignRequestInterceptor.java
  notification-service/src/main/java/com/piggymetrics/notification/config/ResourceServerConfig.java
  notification-service/src/main/java/com/piggymetrics/notification/controller/ErrorResponse.java
  notification-service/src/main/java/com/piggymetrics/notification/controller/GlobalExceptionHandler.java
  notification-service/src/main/java/com/piggymetrics/notification/controller/RecipientController.java
  notification-service/src/main/java/com/piggymetrics/notification/domain/Frequency.java
  notification-service/src/main/java/com/piggymetrics/notification/domain/NotificationSettings.java
  notification-service/src/main/java/com/piggymetrics/notification/domain/NotificationType.java
  notification-service/src/main/java/com/piggymetrics/notification/domain/Recipient.java
  notification-service/src/main/java/com/piggymetrics/notification/repository/RecipientRepository.java
  notification-service/src/main/java/com/piggymetrics/notification/repository/RecipientRepositoryCustom.java
  notification-service/src/main/java/com/piggymetrics/notification/repository/RecipientRepositoryImpl.java
  notification-service/src/main/java/com/piggymetrics/notification/repository/converter/FrequencyReaderConverter.java
  notification-service/src/main/java/com/piggymetrics/notification/repository/converter/FrequencyWriterConverter.java
  notification-service/src/main/java/com/piggymetrics/notification/service/EmailService.java
  notification-service/src/main/java/com/piggymetrics/notification/service/EmailServiceImpl.java
  notification-service/src/main/java/com/piggymetrics/notification/service/NotificationService.java
  notification-service/src/main/java/com/piggymetrics/notification/service/NotificationServiceImpl.java
  notification-service/src/main/java/com/piggymetrics/notification/service/RecipientService.java
  notification-service/src/main/java/com/piggymetrics/notification/service/RecipientServiceImpl.java
  notification-service/src/main/resources/application.yml
  notification-service/src/main/resources/bootstrap.yml
  notification-service/src/test/java/com/piggymetrics/notification/NotificationServiceApplicationTests.java
  notification-service/src/test/java/com/piggymetrics/notification/controller/RecipientControllerTest.java
  notification-service/src/test/java/com/piggymetrics/notification/repository/RecipientRepositoryTest.java
  notification-service/src/test/java/com/piggymetrics/notification/service/EmailServiceImplTest.java
  notification-service/src/test/java/com/piggymetrics/notification/service/NotificationServiceImplTest.java
  notification-service/src/test/java/com/piggymetrics/notification/service/RecipientServiceImplTest.java
  notification-service/src/test/resources/application.yml
Labels: fix, feat

#71 [Feat] account service에 대한 테스트 코드 작성 및 mongodb 트랜잭션 적용
  account-service/src/main/java/com/piggymetrics/account/config/MongoConfig.java
  account-service/src/main/java/com/piggymetrics/account/domain/Account.java
  account-service/src/main/java/com/piggymetrics/account/domain/User.java
  account-service/src/main/java/com/piggymetrics/account/repository/AccountRepository.java
  account-service/src/main/java/com/piggymetrics/account/service/AccountService.java
  account-service/src/test/java/com/piggymetrics/account/controller/AccountControllerTest.java
  account-service/src/test/java/com/piggymetrics/account/service/AccountServiceTest.java
  config/src/main/resources/shared/account-service.yml
  docker-compose-test.yml
Labels: fix, feat, refactor

#78 [Fix] 모니터링 설정 배포 환경으로 변경
  docker-compose-test.yml
  prometheus.yml
Labels: fix, feat

#79 [fix] 타켓 url 형식, 포트번호 수정
  prometheus.yml
Labels: fix, hot fix

#81 fix: 환율 api 변경 및 적용
  statistics-service/src/main/java/com/piggymetrics/statistics/StatisticsApplication.java
  statistics-service/src/main/java/com/piggymetrics/statistics/client/ExchangeRatesClient.java
  statistics-service/src/main/java/com/piggymetrics/statistics/client/ExchangeRatesClientFallback.java
  statistics-service/src/main/java/com/piggymetrics/statistics/controller/ExchangeRatesController.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/ExchangeRate.java
  statistics-service/src/main/java/com/piggymetrics/statistics/domain/ExchangeRatesContainer.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/ExchangeRatesService.java
  statistics-service/src/main/java/com/piggymetrics/statistics/service/StatisticsService.java
  statistics-service/src/test/java/com/piggymetrics/statistics/StatisticsServiceApplicationTests.java
  statistics-service/src/test/java/com/piggymetrics/statistics/client/ExchangeRatesClientTest.java
  statistics-service/src/test/java/com/piggymetrics/statistics/service/ExchangeRatesServiceImplTest.java
Labels: hot fix

#82 fix: statistics-service 잘못된 임포트 삭제
  statistics-service/src/main/java/com/piggymetrics/statistics/StatisticsApplication.java
Labels: fix

#84 fix: USD 통계 계산 문제 해결
  gateway/src/main/resources/static/js/launch.js
Labels: fix
